apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-hello-world
  template:
    metadata:
      labels:
        app: flutter-hello-world
    spec:
      containers:
      - name: flutter-hello-world
        image: nginx:alpine  # We'll use nginx to serve our Flutter web build
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flutter-hello-world-service
spec:
  type: NodePort
  selector:
    app: flutter-hello-world
  ports:
    - port: 80
      targetPort: 80
