name: hello_world_app
description: A Flutter project for testing Google OAuth 2.0 login on the web.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The Google Sign-In package configured for web
  google_sign_in: ^5.0.7

  # Material Design icons package
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for Flutter apps
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
